import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Gestion Documentos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      {/* Usamos flex de forma horizontal para que el sidebar quede al lado del contenido */}
      <body className="antialiased min-h-dvh flex bg-slate-50 text-slate-900">
        {children}
      </body>
    </html>
  );
}
